Controllers/HomeController.cs
using Microsoft.AspNet.Mvc;
using TeamY.Models;
using TeamY.Services;

namespace TeamY.Controllers
{
    public class HomeController : Controller
    {
        readonly IUserService _nameService;
        readonly IOctopusService _octopusService;
        readonly ILocationDetailsService _locationDetailsService;

        public HomeController(IUserService nameService, IOctopusService octopusService, ILocationDetailsService locationDetailsService)
        {
            _nameService = nameService;
            _octopusService = octopusService;
            _locationDetailsService = locationDetailsService;
        }

        public IActionResult Index()
        {
            var model = new HomeModel(_nameService.Current(User))
            {
                LatestDeployments = _octopusService.GetDeployments(5),
                LocationDetails = _locationDetailsService.GetLocationDetails()
            };
            return View(model);
        }

        public IActionResult LocationDetails()
        {
            var model = new HomeModel(_nameService.Current(User))
            {
                LatestDeployments = _octopusService.GetDeployments(5),
                LocationDetails = _locationDetailsService.GetLocationDetails()
            };
            return View("LocationDetails", model);
        }
    }
}

Controllers/LunchManagerController.cs
using System;
using System.Linq;
using Microsoft.AspNet.Mvc;
using TeamY.Domain;
using TeamY.Infrastructure;
using TeamY.Models;

namespace TeamY.Controllers
{
    public class LunchManagerController : Controller
    {
        private readonly TeamyDbContext _dbContext;

        public LunchManagerController(TeamyDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IActionResult Add()
        {
            var lunch = new LunchModel();
            lunch.Date = DateTime.Today;
            return View("Add", lunch);
        }

        [HttpPost]
        public IActionResult Add([Bind] LunchModel lunchModel)
        {
            if (string.IsNullOrEmpty(lunchModel.Menu) && string.IsNullOrEmpty(lunchModel.ImageSrc))
            {
                return RedirectToAction("Add", lunchModel);
            }
            if (lunchModel.Date <= DateTime.Today.AddYears(-1))
            {
                return RedirectToAction("Add", lunchModel);
            }
            var lunch = new Lunch() { Date = lunchModel.Date, Id = Guid.NewGuid(), Menu = lunchModel.Menu, ImageSrc = lunchModel.ImageSrc };
            _dbContext.Lunches.Add(lunch);
            _dbContext.SaveChanges();
            return Ok();


        }

        public IActionResult Delete(Guid id)
        {
            var lunch = _dbContext.Lunches.FirstOrDefault(x => x.Id == id);
            if (lunch == null)
            {
                return RedirectToAction("Index");
            }
            return View("Delete", lunch);
        }

        [HttpPost]
        public IActionResult Delete([Bind] Lunch lunch)
        {
            _dbContext.Lunches.Remove(lunch);
            return Ok(_dbContext.SaveChanges());
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            var lunches = _dbContext.Lunches.OrderByDescending(x => x.Date).Take(10);
            return View("Index", lunches);
        }
    }
}

Views/Home/Index.cshtml
@{
    Layout = "/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Home Page";
}

@model TeamY.Models.HomeModel

<div id="top-nav">
    <header>
        <a href="/"><i class="icon-codehouse"></i></a>
        <div class="username">
            <p>@Model.Name</p>
            <p class="login">@Html.ActionLink("Logout", "Logout", "Account")</p>
        </div>
        <div class="login-out">

        </div>
        <div class="nav">
            <ul>
                <li><a href="#">Codehouse<i class="icon-codehouse"></i></a></li>
                <li><a href="#">Galaxy<i class="icon-galaxy"></i></a></li>
                <li><a href="#">Pandora<i class="icon-pandora"></i></a></li>
                <li><a href="#">LEGO<i class="icon-lego"></i></a></li>
                <li><a href="#">Admin<i class="icon-business"></i></a></li>
            </ul>
        </div>

    </header>

</div>

<div id="wrapper">

    <main>
        <!-- BEGIN: Overview -->
        <section class="overview">
            <div class="location--table">
                <div class="location-stats">
                    <h2>Location</h2>
                    <div class="data-list">
                        <ul id="location-list">
                            <!--BEGIN Location -->
                            <li>
                                <i class="icon-business"></i>
                                <span>10</span>
                                <span>Meeting</span>
                            </li>
                            <!--END Profile -->
                            <!--BEGIN Location -->
                            <li>
                                <i class="icon-lunch"></i>
                                <span>3</span>
                                <span>Lunch</span>
                            </li>
                            <!--END Profile --> <!--BEGIN Location -->
                            <li>
                                <i class="icon-working-at-home"></i>
                                <span>2</span>
                                <span>Home</span>

                            </li>
                            <!--END Profile -->
                            <!--END Profile --> <!--BEGIN Location -->
                            <li>
                                <i class="icon-day-off"></i>
                                <span>2</span>
                                <span>Day Off</span>
                            </li>
                            <!--END Profile -->
                        </ul>
                    </div>
                    @Html.ActionLink("See all", "LocationDetails")
                </div>

            </div>
            <div class="mood--table">
                <div class="mood-stats">
                    <h2>Mood</h2>
                    <div class="mood-container">
                        <div class="mood-icon">
                            <i class="icon-happy"></i>
                        </div>
                        <div class="mood-data">4.2</div>
                    </div>
                    @Html.ActionLink("See all", "LocationDetails")
                </div>
            </div>
            <div class="lunch--table">
                <div class="lunch-stats">
                    <h2>Todays lunch<i class="icon-lunch"></i> </h2>

                    <div class="lunch-content" id="lunch-content">
                    </div>
                    @Html.ActionLink("Manage", "Index", "LunchManager")
                </div>
            </div>
            <div class="deployment--table">
                <h2>Last @Model.LatestDeployments.Deployments.Count Deployments <span>(@Model.LatestDeployments.TotalNumber)</span></h2>
                <ul>
                    @foreach (var deployment in Model.LatestDeployments.Deployments)
                    {
                        <li>
                            @deployment.Project.Name (@deployment.Version)
                            <span>To @deployment.Enviroment.Name on @deployment.Created</span>
                        </li>
                    }
                </ul>
            </div>
        </section>
        <!-- END: Overview -->
        <!-- BEGIN: Location settings -->
        <section class="location--settings">
            <div class="location--settings--container">
                <div class="profile-img">
                    <img src="@Model.UserImage" alt="">
                </div>
                <div class="profile-settings">
                    <div class="location">
                        <h2>@Model.Name</h2>
                        <div class="title">Status</div>
                        <div class="option">
                            <select id="updateStatus">
                                <option value="work">Work</option>
                                <option value="home">Home</option>
                            </select>
                            <i class="icon-lunch"></i>
                        </div>
                    </div>
                    <div class="mood">
                        <div class="title">Mood</div>
                        <div class="option">
                            <select id="updateMood">
                                <option value="happy" data-image="/img/icons/happy.png">Happy</option>
                                <option value="not happy" data-image="/img/icons/nothappy.png">Not Happy</option>
                            </select>
                            <i id="selected-mood-icon" class="icon-mad"></i>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- END: Location settings -->
    </main>
    <footer></footer>
</div> 

Views/Home/LocationDetails.cshtml
@model TeamY.Models.HomeModel

@{
    Layout = "/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Info Page";
}
<div id="top-nav">
    <header>
        <a href="/"><i class="icon-codehouse"></i></a>
        <div class="username">
            <p>@Model.Name</p>
            <p class="login">@Html.ActionLink("Logout", "Logout", "Account")</p>
        </div>
        <div class="login-out">

        </div>
        <div class="nav">
            <ul>
                <li><a href="#">Codehouse<i class="icon-codehouse"></i></a></li>
                <li><a href="#">Galaxy<i class="icon-galaxy"></i></a></li>
                <li><a href="#">Pandora<i class="icon-pandora"></i></a></li>
                <li><a href="#">LEGO<i class="icon-lego"></i></a></li>
                <li><a href="#">Admin<i class="icon-business"></i></a></li>
            </ul>
        </div>

    </header>

</div>

<div id="wrapper">
    <main>
        <section class="location--details">
            <div class="location--details--container">
                <div class="data-list">
                    <ul>
                        @foreach (var user in Model.LocationDetails)
            {
                <!--BEGIN Profile -->
                            <li>
                                <div class="profile-img">
                                    <img src="@user.UserImage" alt="">
                                </div>
                                <div class="profile-location--icon"><i class="@user.StateClass"></i></div>
                                <div class="profile-location">@user.State</div>
                                <div class="profile--mood--icon">
                                    <i class="@user.Mood"></i>
                                </div>
                            </li>
                <!--END Profile -->
                        }
                    </ul>
                </div>
            </div>
        </section>
    </main>
    <footer></footer>
</div> 